# action.yml
name: 'Cloudsmith'
description: 'Interact with Cloudsmith repositories'
inputs:
  api-key:  
    description: 'The Cloudsmith API Key in the Github Secrets repository settings.'
    required: true
  command:  
    description: 'The desired action with cloudsmith (push, list, etc)'
    required: true
    default: help
  format:  
    description: 'The package format (deb,npm,maven, etc)'
    required: true
  owner:  
    description: 'The organization that owns the repository'
    required: true
  repo:  
    description: 'The repository slug'
    required: true
  file:  
    description: 'The package file to be pushed'
    required: true
  distro:  
    description: 'Debian: The distribution (ubuntu)'
    required: false
  release:  
    description: 'Debian: The named version of the release (xenial)'
    required: false

runs:
  using: 'docker'
  image: 'Dockerfile'
  args: # these map in order with entrypoint.sh
    - ${{ inputs.api-key }}
    - ${{ inputs.command }}
    - ${{ inputs.format }}
    - ${{ inputs.owner }}
    - ${{ inputs.repo }}
    - ${{ inputs.file }}
    - ${{ inputs.distro }}
    - ${{ inputs.release }}