name: Cloudsmith Push
on: 
  push:
    branches:
      - master
    tags:
      - '*'
jobs:
  push_raw:
    runs-on: ubuntu-latest
    name: Push demo
    steps:
    - name: Push
      id: push
      uses: AutoModality/action-cloudsmith@master
      with:
        command: 'push'
        format: 'deb'
        owner: 'automodality'
        repo: 'trial'
        distro: 'ubuntu'
        release: 'xenial'
        file: 'missing-0.0.0_amd64.deb'

