name: Cloudsmith Push
on: push
jobs:
  push:
    runs-on: ubuntu-latest
    name: Push demo
    steps:
    - name: Push
      id: push
      uses: AutoModality/action-cloudsmith@BB-762
      with:
        api-key: ${{ secrets.CLOUDSMITH_API_KEY }}
        command: 'push'
        format: 'deb'
        owner: 'automodality'
        repo: 'trial'
        distro: 'ubuntu'
        release: 'xenial'
        file: 'action.yml'

