name: Push RPM
on: push
jobs:
  push:
    runs-on: ubuntu-latest
    name: RPM Push Demo
    steps:
      - uses: actions/checkout@v1
      - name: Push
        id: push
        uses: cloudsmith-io/action@master
        with:
          api-key: ${{ secrets.CLOUDSMITH_API_KEY }}
          command: "push"
          format: "rpm"
          owner: "cloudsmith"
          repo: "actions"
          distro: "any-distro"
          release: "any-version"
          republish: "true" # needed since version is not changing
          file: "test/fixtures/cloudsmith-rpm-example-1.0-1.x86_64.rpm" #real file that will repeat versions
