name: Push Docker
on: push
jobs:
  push:
    runs-on: ubuntu-latest
    name: Docker Push Demo
    steps:
    - uses: actions/checkout@v1
    - name: Push
      id: push
      uses: AutoModality/action-cloudsmith@BB-771
      with:
        api-key: ${{ secrets.CLOUDSMITH_API_KEY }}
        command: 'push'
        format: 'docker'
        owner: 'automodality'
        repo: 'trial'
        republish: 'true' # needed since version is not changing
        file: 'test/fixture/alpine-docker-test.tar.gz' #alpine image saved to file

